### PR TITLE
Fixed Flink Job Manager Port

### PR DESCRIPTION
**Pull request by eschizoid**
The purpose of this PR is the following:
- Fix wrong port number for `Flink Job Manager`
- Add extra folder/files to `gitignore` file
- Update `Flink` version to latest

### CODE REVIEW

**Comment by jgrier** [comment]
That is not the Flink JobManager port.  Just a connection to a socket server where you can type commands.  Could be any port.

**Comment by eschizoid** [comment]
@jgrier If you run the example as they are right now, they will fail. What I had to do in order to make them work was matching the port specified on `flink-conf.yaml`:

```
jobmanager.rpc.port: 6123
```

and the one specified on `OsconJob.java`:

```
KeyedStream<ControlMessage, Tuple> controlStream = env.socketTextStream("localhost", 6123)
```

If I dont do that, the examples doesn't work

**Comment by jgrier** [comment]
Ahh, sorry about that.  This repo was part of a demo I did a while back at OSCON.

Anyway, it's designed to connect to a socket server on port 9999 - not the Flink Job Manager.

The idea is to do

``` bash
nc -lk 9999
```

And then run the job.  You then can type commands at the terminal and affect the output of the job.  I hope that helps.

I should definitely put some docs around this.

**Comment by jgrier** [comment]
I'll comment out the lines that depend on the socket server for now so it's runnable without further instruction.

**Pull request closed without merging**
